SMALLTALK_LIST = [
    "Are you my appendix? I dont know what you do or how you work, but I feel like I should take you out.",
    "Somebody call the cops because its got to be illegal to look that good!",
    "If you were a vegetable, youd be a CUTEcumber!",
    "Is it hot in here or is it just you?",
    "If you were a triangle youd be an acute one",
    "Hey girl, are you a beaver? Cause damn!",
    "Are you an orphanage? Because I want to give you kids.",
    "Is that a mirror in your pocket? Cause I can see myself in your pants.",
    "Hey, youre pretty and Im cute. Together wed be Pretty Cute.",
    "Would you grab my arm, so I can tell my friends Ive been touched by an angel?",
    "If you were a transformer youd be Optimus fine",
    "Are you a banana? Because you are very appealing.",
    "Was you father an alien? Because theres nothing else like you on Earth!",
    "Can you take off your clothes so I can see where you hide your angel wings?",
    "If nothing lasts forever, will you be my nothing?",
    "I couldnt help noticing that you look a lot like my next girlfriend.",
    "Are you French? Because Eiffel for you.",
    "If you were a fruit youd be a fine apple",
    "Are you from Tennessee? Because youre the only 10 I see!",
    "If I flip this coin, what are the chances of me getting head?",
    "Are you a parking ticket? Because youve got FINE written all over you.",
    "I must be in a museum, because you truly are a work of art.",
    "Do you believe in love at first sight—or should I walk by again?",
    "Im no photographer, but I can picture us together.",
    "Its a good thing I have my library card because I am totally checking you out.",
    "Is this the Hogwarts Express? Because it feels like you and I are headed somewhere magical.",
    "Do you like Star Wars? Because Yoda only one for me!",
    "I was wondering if youre an artist because you were so good at drawing me in.",
    "You know what you would look really beautiful in? My arms",
    "Ive heard it said that kissing is the language of love. Would you care to have a conversation with me about it sometime?",
    "I believe in following my dreams. Can I have your Instagram?",
    "Do you ever get tired from running through my thoughts all night?",
    "Your hand looks heavy, can I hold it for you?",
    "Im not usually religious, but when I saw you, I knew you were the answer to my prayers",
    "Are you a dictionary? Cause youre adding meaning to my life.If I were a cat, Id spend all nine of my lives with you.",
    "I seem to have lost my number, can I have yours?",
    "Do you have a name, or can I just call you mine?",
    "I hope you know CPR, because you are taking my breath away!",
    "Are you a loan? Cause youve got my interest!",
    "Remember me? Oh, thats right, Ive only met you in my dreams",
    "You must be made of cheese. Because youre looking Gouda tonight!",
    "You must be exhausted. Youve been running through my mind all day.",
    "Im writing a term paper on the finer things in life, and I was wondering if I could interview you.",
    "Kiss me if Im wrong, but dinosaurs still exist, right?",
    "You are hotter than the bottom of my laptop.",
    "Excuse me, do you know how much a polar bear weighs? No? Me neither but it breaks the ice.",
    "Hi, Im writing a phone book, can I have your number?",
    "Are you a Wi-Fi hotspot? Because I feel a connection.",
    "Is your name Wally? Because someone like you is hard to find.",
    "I went to my doctor and he told me I have a serious deficiency of Vitamin U!"]
